### ISSUE TITLE
Cannot resolve symbol GetLines

### ISSUE THREAD

**Issue by tortelloid** [UberFoX/SputnikAsm#2]
GetLines definition is missing from AStringUtils

**Comment by UberFoX** [comment]
Change it to UStringUtils then (or Sputniik.UStringUtils if not importing Sputnik)
________________________________
From: tortelloid ***@***.***>
Sent: 19 April 2021 9:13 AM
To: UberFoX/SputnikAsm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UberFoX/SputnikAsm] Cannot resolve symbol GetLines (#2)


GetLines definition is missing from AStringUtils

**Comment by UberFoX** [comment]
Use "UStringUtils.GetLines" nothing in the project uses the method you said.

**Comment by tortelloid** [comment]
I see i used the wrong class thanks
